# Generated by Django 3.1.7 on 2021-07-06 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_name_text', models.CharField(max_length=200)),
                ('dob_date', models.DateTimeField(verbose_name='date of birth')),
            ],
        ),
        migrations.CreateModel(
            name='Tennis_Practices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_date', models.DateTimeField(verbose_name='date practice')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennisapp.coach')),
            ],
        ),
    ]
